import { CostConfig, ExpenseItem, Product, StockLog } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PROD-001',
    sku: 'KT-RED-1000',
    name: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    price: 35,
    costEstimate: 14.85,
    stock: 42,
    bottleSizeMl: 1000,
    description: 'สูตรยอดนิยม เข้มข้น กลมกล่อม ผสมฝาแดงและโค้กเย็นเจี๊ยบ',
    active: true,
  },
  {
    id: 'PROD-002',
    sku: 'KT-BM-1000',
    name: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    price: 35,
    costEstimate: 13.95,
    stock: 36,
    bottleSizeMl: 1000,
    description: 'สูตรบีเอ็ม รสชาติเฉพาะตัว หวานอมเปรี้ยวด้วยบ๊วยเค็ม 9 เม็ด',
    active: true,
  },
  {
    id: 'PROD-003',
    sku: 'KT-RAW-1000',
    name: 'น้ำกระท่อมดิบแท้ 100% (1,000ml)',
    formulaType: 'OTHER',
    price: 30,
    costEstimate: 8.5,
    stock: 18,
    bottleSizeMl: 1000,
    description: 'น้ำกระท่อมสกัดบริสุทธิ์ ไม่ผสม สำหรับสายชอบปรุงแต่งสูตรเอง',
    active: true,
  },
  {
    id: 'PROD-004',
    sku: 'KT-RED-1500',
    name: 'กระท่อมต้ม สูตรฝาแดง ไซส์จัมโบ้ (1,500ml)',
    formulaType: 'RED',
    price: 50,
    costEstimate: 21.2,
    stock: 15,
    bottleSizeMl: 1500,
    description: 'ขวดใหญ่สุดคุ้ม จุใจ สดใหม่ทุกวัน',
    active: true,
  },
  {
    id: 'PROD-005',
    sku: 'KT-BM-1500',
    name: 'กระท่อมต้ม สูตร BM ไซส์จัมโบ้ (1,500ml)',
    formulaType: 'BM',
    price: 50,
    costEstimate: 19.8,
    stock: 12,
    bottleSizeMl: 1500,
    description: 'ขวดใหญ่ จุใจ หวานชื่นใจ บ๊วยเน้นๆ',
    active: true,
  }
];

export const INITIAL_CONFIG: CostConfig = {
  // Common Costs
  leafCostPerKg: 100,
  bottleAndStickerCost: 4,
  overheadCostPerBottle: 2,
  
  // RED Formula
  redCokeCostPerLiter: 22,
  redSyrupCostPerBottle60ml: 54,
  redSellingPrice: 35,
  
  // BM Formula
  bmCokeCostPerLiter: 22,
  bmSyrupCostPerBottle60ml: 34,
  bmPlumCostPerPiece: 0.5,
  bmSellingPrice: 35,
  
  // Recipe Ratios (per standard batch of 3L raw)
  redRawRatio: 3,
  redCokeRatio: 1,
  redSyrupMl: 20,
  
  bmRawRatio: 3,
  bmCokeRatio: 1,
  bmSyrupMl: 20,
  bmPlumCount: 9,
  
  // Boiling Defaults
  boilRatioWaterToLeaf: 22,
  boilExtractPercent: 80,
  standardBottleSizeMl: 1000,
};

// Helper function to generate realistic past dates
const getDateDaysAgo = (daysAgo: number, hour = 14, min = 30): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
};

export const INITIAL_STOCK_LOGS: StockLog[] = [
  // Today's Sales
  {
    id: 'SL-1001',
    timestamp: getDateDaysAgo(0, 11, 20),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 3,
    remainingStock: 42,
    unitPrice: 35,
    totalPrice: 105,
    cost: 44.55,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'คุณเบิร์ด หน้าร้าน',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1002',
    timestamp: getDateDaysAgo(0, 13, 10),
    type: 'OUT',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 2,
    remainingStock: 36,
    unitPrice: 35,
    totalPrice: 70,
    cost: 27.9,
    paymentMethod: 'CASH',
    customerOrLot: 'ลูกค้าประจำ ซอย 5',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1003',
    timestamp: getDateDaysAgo(0, 15, 45),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 5,
    remainingStock: 37,
    unitPrice: 35,
    totalPrice: 175,
    cost: 74.25,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'พี่ต้อม อู่ช่าง',
    notes: 'สั่งจัดส่งแกร็บ',
  },
  // Production Lot received today
  {
    id: 'SL-1004',
    timestamp: getDateDaysAgo(0, 9, 30),
    type: 'IN',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 25,
    remainingStock: 45,
    unitPrice: 0,
    totalPrice: 0,
    cost: 371.25,
    paymentMethod: 'CASH',
    customerOrLot: 'LOT-20260912-M1',
    notes: 'ต้มเช้า ชุดที่ 1 น้ำดิบ 18L',
  },
  {
    id: 'SL-1005',
    timestamp: getDateDaysAgo(0, 10, 0),
    type: 'IN',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 20,
    remainingStock: 38,
    unitPrice: 0,
    totalPrice: 0,
    cost: 279.0,
    paymentMethod: 'CASH',
    customerOrLot: 'LOT-20260912-M2',
    notes: 'ต้มเช้า ชุดที่ 2 น้ำดิบ 15L ผสมบ๊วย',
  },
  // Yesterday's Sales (Day 1 ago)
  {
    id: 'SL-1006',
    timestamp: getDateDaysAgo(1, 12, 15),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 8,
    remainingStock: 28,
    unitPrice: 35,
    totalPrice: 280,
    cost: 118.8,
    paymentMethod: 'CASH',
    customerOrLot: 'หน้าร้าน',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1007',
    timestamp: getDateDaysAgo(1, 14, 20),
    type: 'OUT',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 6,
    remainingStock: 24,
    unitPrice: 35,
    totalPrice: 210,
    cost: 83.7,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'คุณเอ็ม ตลาดนัด',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1008',
    timestamp: getDateDaysAgo(1, 18, 50),
    type: 'OUT',
    productId: 'PROD-004',
    productName: 'กระท่อมต้ม สูตรฝาแดง ไซส์จัมโบ้ (1,500ml)',
    formulaType: 'RED',
    quantity: 4,
    remainingStock: 15,
    unitPrice: 50,
    totalPrice: 200,
    cost: 84.8,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'กลุ่มไรเดอร์',
    notes: 'POS Sale',
  },
  // 2 Days ago
  {
    id: 'SL-1009',
    timestamp: getDateDaysAgo(2, 11, 40),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 10,
    remainingStock: 36,
    unitPrice: 35,
    totalPrice: 350,
    cost: 148.5,
    paymentMethod: 'CASH',
    customerOrLot: 'ทีมงานก่อสร้าง',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1010',
    timestamp: getDateDaysAgo(2, 16, 10),
    type: 'OUT',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 8,
    remainingStock: 30,
    unitPrice: 35,
    totalPrice: 280,
    cost: 111.6,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'คุณกอล์ฟ',
    notes: 'POS Sale',
  },
  // 3 Days ago
  {
    id: 'SL-1011',
    timestamp: getDateDaysAgo(3, 13, 0),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 12,
    remainingStock: 46,
    unitPrice: 35,
    totalPrice: 420,
    cost: 178.2,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'โต๊ะสนุ๊กเกอร์ปากซอย',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1012',
    timestamp: getDateDaysAgo(3, 17, 30),
    type: 'OUT',
    productId: 'PROD-003',
    productName: 'น้ำกระท่อมดิบแท้ 100% (1,000ml)',
    formulaType: 'OTHER',
    quantity: 4,
    remainingStock: 20,
    unitPrice: 30,
    totalPrice: 120,
    cost: 34.0,
    paymentMethod: 'CASH',
    customerOrLot: 'คุณเป็ด',
    notes: 'น้ำดิบเอาไปต้มเอง',
  },
  // 4 Days ago
  {
    id: 'SL-1013',
    timestamp: getDateDaysAgo(4, 12, 10),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 7,
    remainingStock: 58,
    unitPrice: 35,
    totalPrice: 245,
    cost: 103.95,
    paymentMethod: 'CASH',
    customerOrLot: 'หน้าร้าน',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1014',
    timestamp: getDateDaysAgo(4, 15, 20),
    type: 'OUT',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 9,
    remainingStock: 38,
    unitPrice: 35,
    totalPrice: 315,
    cost: 125.55,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'พี่หนุ่ม วินมอไซค์',
    notes: 'POS Sale',
  },
  // 5 Days ago
  {
    id: 'SL-1015',
    timestamp: getDateDaysAgo(5, 14, 0),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 14,
    remainingStock: 65,
    unitPrice: 35,
    totalPrice: 490,
    cost: 207.9,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'ร้านของชำซอย 8',
    notes: 'รับไปขายต่อ',
  },
  // 6 Days ago
  {
    id: 'SL-1016',
    timestamp: getDateDaysAgo(6, 13, 40),
    type: 'OUT',
    productId: 'PROD-002',
    productName: 'กระท่อมต้ม สูตร BM (1,000ml)',
    formulaType: 'BM',
    quantity: 11,
    remainingStock: 47,
    unitPrice: 35,
    totalPrice: 385,
    cost: 153.45,
    paymentMethod: 'CASH',
    customerOrLot: 'ลูกค้าประจำ',
    notes: 'POS Sale',
  },
  {
    id: 'SL-1017',
    timestamp: getDateDaysAgo(6, 19, 10),
    type: 'OUT',
    productId: 'PROD-001',
    productName: 'กระท่อมต้ม สูตรฝาแดง (1,000ml)',
    formulaType: 'RED',
    quantity: 6,
    remainingStock: 79,
    unitPrice: 35,
    totalPrice: 210,
    cost: 89.1,
    paymentMethod: 'TRANSFER',
    customerOrLot: 'คุณนนท์',
    notes: 'POS Sale',
  },
];

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: 'EXP-2001',
    timestamp: getDateDaysAgo(0, 8, 30),
    category: 'โค้ก',
    description: 'ซื้อโค้กขวดลิตร 1.5L x 12 ขวด',
    amount: 396,
    quantity: 18,
    unit: 'ลิตร',
    notes: 'แม็คโคร',
  },
  {
    id: 'EXP-2002',
    timestamp: getDateDaysAgo(1, 9, 0),
    category: 'ใบกระท่อม',
    description: 'รับใบกระท่อมก้านแดงสดเกรด A',
    amount: 500,
    quantity: 5,
    unit: 'กก.',
    notes: 'สวนพี่พร ชุมพร',
  },
  {
    id: 'EXP-2003',
    timestamp: getDateDaysAgo(2, 10, 15),
    category: 'ยาแก้ไอฝาแดง',
    description: 'ยาแก้ไอฝาแดง อัลเลอร์แกน 60ml x 10 ขวด',
    amount: 540,
    quantity: 10,
    unit: 'ขวด',
    notes: 'ร้านยาสหเภสัช',
  },
  {
    id: 'EXP-2004',
    timestamp: getDateDaysAgo(3, 14, 0),
    category: 'ขวด/สติกเกอร์',
    description: 'ขวดพลาสติกใส 1,000ml + ฝาล็อค พร้อมสติกเกอร์ 100 ชุด',
    amount: 400,
    quantity: 100,
    unit: 'ชุด',
    notes: 'โรงงานแพ็คเกจจิ้ง',
  },
  {
    id: 'EXP-2005',
    timestamp: getDateDaysAgo(4, 11, 30),
    category: 'ยาแก้ไอ BM',
    description: 'ยาแก้ไอสูตร BM 60ml x 10 ขวด',
    amount: 340,
    quantity: 10,
    unit: 'ขวด',
    notes: 'คลังยาเจริญผล',
  },
  {
    id: 'EXP-2006',
    timestamp: getDateDaysAgo(5, 16, 0),
    category: 'บ๊วย',
    description: 'บ๊วยหวานเค็มเกรดพรีเมียม 1 ถุงใหญ่',
    amount: 120,
    quantity: 240,
    unit: 'เม็ด',
    notes: 'ตลาดไทย',
  },
  {
    id: 'EXP-2007',
    timestamp: getDateDaysAgo(6, 17, 30),
    category: 'แก๊ส/ไฟ',
    description: 'เปลี่ยนถังแก๊ส ปตท. 15 กก.',
    amount: 430,
    quantity: 1,
    unit: 'ถัง',
    notes: 'ร้านแก๊สปากซอย',
  },
];
